name: Reusable - Tests

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        required: false
        type: string
        default: '3.11'
      install-command:
        description: 'Command to install project dependencies'
        required: false
        type: string
        default: 'pip install -e ".[dev]"'
      upload-coverage:
        description: 'Whether to upload coverage to codecov'
        required: false
        type: boolean
        default: true
      comment-on-pr:
        description: 'Post coverage comment on Pull Requests'
        required: false
        type: boolean
        default: true

jobs:
  comprehensive-tests:
    runs-on: ubuntu-latest
    name: Comprehensive Tests
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        ${{ inputs.install-command }}
    
    - name: Run all tests and generate reports
      id: run-tests
      run: |
        export PYTHONPATH="${PYTHONPATH}:$(pwd)"
        # 
        # 运行所有测试 (unit 和 integration)
        # - 生成 pytest.xml 供 PR 评论使用
        # - 生成 coverage.xml 供 Codecov 和 PR 评论使用
        #
        pytest tests/unit/ tests/integration/ \
          --cov=. \
          --cov-report=xml:coverage.xml \
          --cov-report=term-missing \
          --junitxml=pytest.xml \
          -v -s --tb=short
    
    - name: Pytest coverage comment
      # 仅在 input 启用时，并且仅在 pull_request 事件上运行
      if: ${{ inputs.comment-on-pr && github.event_name == 'pull_request' }}
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-xml-coverage-path: ./coverage.xml
        junitxml-path: ./pytest.xml
    
    - name: Upload coverage
      if: ${{ inputs.upload-coverage }}
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
